# Generated by Django 3.1.2 on 2022-06-14 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='data creazione')),
                ('authors', models.ManyToManyField(related_name='diaries', to=settings.AUTH_USER_MODEL, verbose_name='autori')),
            ],
            options={
                'verbose_name': 'diario',
                'verbose_name_plural': 'diari',
                'db_table': 'diaries',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000, verbose_name='testo')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='data creazione')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='data di modifica')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='communications.diary', verbose_name='diario')),
            ],
            options={
                'verbose_name': 'pagina',
                'verbose_name_plural': 'pagine',
                'db_table': 'pages',
            },
        ),
    ]
