# Generated by Django 3.1.2 on 2022-02-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dpc',
            field=models.BooleanField(default=False, verbose_name='Consenso trattamento dati'),
        ),
    ]
