# Generated by Django 3.1.2 on 2022-02-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_dpc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dpc',
            field=models.BooleanField(blank=True, default=False, verbose_name='Consenso trattamento dati'),
        ),
    ]
