# Generated by Django 3.1.2 on 2021-11-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='group',
            field=models.CharField(blank=True, default='tazan5', max_length=6, verbose_name='gruppo'),
        ),
    ]
