# Generated by Django 3.1.2 on 2021-11-27 22:51

from django.db import migrations, models
import experiences.models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_auto_20211127_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='group',
            field=models.CharField(blank=True, default='9lnb2e', max_length=6, verbose_name='gruppo'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/%Y/%m/%d', verbose_name='immagine'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=experiences.models.NameField(max_length=300, primary_key=True, serialize=False, verbose_name='nome'),
        ),
    ]
