# Generated by Django 3.1.2 on 2021-11-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0005_auto_20211129_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='unipiinternship',
            name='attendance',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='presenze'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unipiinternship',
            name='place',
            field=models.CharField(default='A', max_length=3, verbose_name='luogo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unipiinternship',
            name='recommended_year',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='anno accademico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='group',
            field=models.CharField(blank=True, default='ertn04', max_length=6, verbose_name='gruppo'),
        ),
        migrations.AlterField(
            model_name='unipiinternship',
            name='ward',
            field=models.CharField(max_length=2, verbose_name='reparto'),
        ),
    ]
