# Generated by Django 3.1.2 on 2021-12-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0007_auto_20211129_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congressconferencesummerschooladditionalattributes',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='congressconferencesummerschooladditionalattributes',
            name='program',
        ),
        migrations.AddField(
            model_name='congressconferencesummerschooladditionalattributes',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='link conferenza'),
        ),
        migrations.AlterField(
            model_name='congressconferencesummerschooladditionalattributes',
            name='link_organization',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='link organizzazione'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='group',
            field=models.CharField(blank=True, default='tho2if', max_length=6, verbose_name='gruppo'),
        ),
    ]
