# Generated by Django 3.1.2 on 2021-12-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0008_auto_20211203_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='group',
            field=models.CharField(blank=True, default='cp9pfu', max_length=6, verbose_name='gruppo'),
        ),
        migrations.AlterField(
            model_name='sfslaberasmusadditionalattributes',
            name='thesis',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='si può scrivere la tesi?'),
        ),
    ]
