# Generated by Django 3.1.2 on 2022-02-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0010_auto_20220214_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='group',
            field=models.CharField(blank=True, default='gnqr51', max_length=6, verbose_name='gruppo'),
        ),
    ]
