# Generated by Django 3.1.2 on 2022-02-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0011_auto_20220214_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='group',
            field=models.CharField(blank=True, default='rv7c6i', max_length=6, verbose_name='gruppo'),
        ),
    ]
