# Generated by Django 3.1.2 on 2022-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0012_auto_20220222_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='group',
            field=models.CharField(blank=True, default='a6ar07', max_length=6, verbose_name='gruppo'),
        ),
    ]
